# Generated by Django 5.0.2 on 2024-02-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=255)),
                ('product_color', models.TextField(max_length=255)),
                ('product_size', models.TextField(max_length=255)),
                ('product_amount', models.IntegerField()),
            ],
        ),
    ]
