# Generated by Django 5.0.2 on 2024-03-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ibovespa_selected', models.BooleanField(default=False)),
                ('dolar_selected', models.BooleanField(default=False)),
                ('receive_method', models.CharField(max_length=50)),
            ],
        ),
    ]
