# Generated by Django 5.0.2 on 2024-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ibov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_user', models.TextField(max_length=255)),
                ('email_user', models.TextField(max_length=255)),
            ],
        ),
    ]
