# Generated by Django 5.0.2 on 2024-03-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ibov', '0002_get_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_product',
            name='dolar_selected',
        ),
        migrations.RemoveField(
            model_name='register_product',
            name='ibovespa_selected',
        ),
    ]
